### ISSUE TITLE
Doesn't offer a way to generate files in current working directory

### ISSUE THREAD

**Issue by IObert** [SAP/yeoman-ui#103]
I noticed that all new projects are created in the home directory of the user under `projects`. 
My suggestion for a better default directory would be the current working directory as yeoman itself works in the same manner. 
If you decide that the home directory should be the default: Could you please add an option to override the default?

**Comment by tomer-epstein** [comment]
Hi Marius,
We really appreciate your feedback.
Currently we work on very basic/critical functionality, but have plans to support overriding the default  in future.. 


Regards,
Tomer

**Comment by tomer-epstein** [comment]
From: Marius  
Sent: Monday, March 9, 2020 5:09 PM
To: Saggi 
Subject: Re: SAP/ yeoman-ui issue #103

Hi Saggi,

my expectation would be that the files will be generated in the current workspace folder, e.g. in the directory that is shows in the explorer. When I reported the issue, the files were always created in a “projects” folder, no matter which workspace what selected in VS Code.

Regards,
Marius

**Comment by slavik-lvovsky** [comment]
Fixed. By default an application is generated in a current workspace
