### ISSUE TITLE
UI doesn't show default value for true/false prompt

### ISSUE THREAD

**Issue by IObert** [SAP/yeoman-ui#104]
I used the following generator: <https://www.npmjs.com/package/generator-easy-ui5>
One of the prompts contains a true/false prompt ("Would you like to create a new ....") where `true` is the default answer. 
The UI, however, doesn't indicate that there would be a default prompt.

<img width="829" alt="Screen Shot 2020-01-14 at 13 46 47" src="https://user-images.githubusercontent.com/1873245/72345983-49a97e00-36d5-11ea-8c00-27109b1244c9.png">

PS: I really love this project!

**Comment by slavik-lvovsky** [comment]
Hi Marius,
We really appreciate your feedback.
Currently we work on very basic/critical functionality, but will answer on all opened issues ASAP

Regards,
Slavik

**Comment by tomer-epstein** [comment]
Hi Marius,
Having a look at your generator code, we have found that theris no default value for this question.

`        }, {
            type: "confirm",
            name: "newdir",
            message: "Would you like to create a new directory for the project?"
        }, {
`
adding default = true. it works!

`        }, {
            type: "confirm",
            name: "newdir",
            message: "Would you like to create a new directory for the project?",
            default: true
        }, {
`
![image](https://user-images.githubusercontent.com/57438361/72502244-85f9ed00-3841-11ea-962f-659fc42c9d4d.png)

**Comment by IObert** [comment]
Interesting, it seems like the yo-cli automatically assumes that there is a default value.
Thanks!
