### ISSUE TITLE
UI doesn't indicate installation of dependecies

### ISSUE THREAD

**Issue by IObert** [SAP/yeoman-ui#105]
I used the following generator: <https://www.npmjs.com/package/generator-easy-ui5>

After setting all the parameters, yeoman runs to scaffold the project. After that, it runs `npm install` in my project which takes a while. 
1. Currently, the UI doesn't indicate that `npm install` is running and the user might think the wizard is broken as it only displays "loading...".
<img width="1112" alt="Screen Shot 2020-01-14 at 13 46 57" src="https://user-images.githubusercontent.com/1873245/72346114-92f9cd80-36d5-11ea-802b-8eac3d4ba200.png">

2. Another issue is that the "Next" button is not disabled during the installation. The user is able to click it multiple times. After each click, the UI shows an additional "loading..." field in the vertical process indicator. This screenshot shows the UI after some clicks:

<img width="1145" alt="Screen Shot 2020-01-14 at 13 45 23" src="https://user-images.githubusercontent.com/1873245/72346103-8e351980-36d5-11ea-93be-ac76309ac230.png">

**Comment by tomer-epstein** [comment]
Hi Marius,

We really appreciate your feedback.
We will handle those 2 issues soon.

Regards,
Tomer

**Comment by tomer-epstein** [comment]
![image](https://user-images.githubusercontent.com/57438361/73842657-abb55900-4825-11ea-846b-6d39a7dbbcfa.png)
