### ISSUE TITLE
Support async functions in generator

### ISSUE THREAD

**Issue by tomer-epstein** [SAP/yeoman-ui#11]

**Comment by perspectivus1** [comment]
Apparently, it's already handled here:
https://github.com/SAP/vscode-webview-rpc-lib/blob/master/src/rpc-common.ts#L90

I'll update `foodq` with an example and then close this issue.

**Comment by perspectivus1** [comment]
I merged the foodq example that includes an async `then()` method (PR https://github.com/SAP/yeoman-ui/pull/18)

**Comment by perspectivus1** [comment]
In the Inquirer docs, the best practice is to use promises, which we support.

However, @idoprz, we don't support the legacy `this.async()`.

We can add this to a *known issues* list, or if you think we should support `this.async()`, feel free to reopen this issue.

**Comment by idoprz** [comment]
although it's not best practice i think we should support it.

**Comment by slavik-lvovsky** [comment]
Fixed
