### ISSUE TITLE
UX - In VSCode the disabled state of the next button is confusing

### ISSUE THREAD

**Issue by IainSAP** [SAP/yeoman-ui#134]
The Next button appears enabled but is non-functional. The button UX (disabled) should be indicate that it is disabled if there are no further pages. Normally this would be greyed out. Might need to improve the UX there.

Next button does not become really enabled until user clicks away rather than once something has been input. 

![image](https://user-images.githubusercontent.com/46536134/74033247-a551e900-49ad-11ea-9f1a-3413f88329df.png)

**Comment by tomer-epstein** [comment]
Hi lain,

We really appreciate your feedback.
Currently we work on very basic/critical functionality, but will answer on all opened issues ASAP

Regards,
Tomer

**Comment by IainSAP** [comment]
Thx @tomer-epstein

**Comment by tomer-epstein** [comment]
Fixed by https://github.com/SAP/yeoman-ui/pull/156
