### ISSUE TITLE
Prompts are executing before input received

### ISSUE THREAD

**Issue by IainSAP** [SAP/yeoman-ui#136]
When using a conditional prompt, the generator prompts continue to execute without waiting for the user input from the previous condition. There is an ordering implied by the inquirer api but this is not being honoured. e.g After 5 seconds the second prompt is rendered but it should wait until the first prompt has received input, it doesn't and continues regardless.
```async prompting() {
    let prompts = [
      {
        when: async prevAnswers => {
            return new Promise((resolve) => {
              setTimeout(() => {
                resolve(true);
              }, 5000);
            });
        }, 
        type: "input",
        name: "hungry",
        message: "Are you hungry?",
        store: true
      },
      {
        when: prevAnswers => {
          if (prevAnswers.hungry === 'ok') {
              console.log('You are something, you took your time...');
              return true;
          }
          return false;
      },
        type: "confirm",
        name: "confirmHungry",
        message: (answers) => {
          return `You said you are ${(answers.hungry ? '' : 'not ')}hungry. Is that right?`;
        },
        store: true,
        validate: (value, answers) => {
          return (value === true ? true : "It must be right");
        },
      }
    ];
    this.answers = await this.prompt(prompts);
  }
```

Also in the case of composition the prompts from subsequent generators are being displayed before input has been received from the first generator.

**Comment by tomer-epstein** [comment]
Hi lain,

We really appreciate your feedback.
This is as design behavior when implementing all questions in 1 prompt.
You may split to couple of prompts then 2nd prompt is excuted only after clicking 'Next' on 1st prompt.


Regards,
Tomer

**Comment by IainSAP** [comment]
Thx for your response @tomer-epstein. If I split into multiple steps, as you recommend, a step be skipped if the condition for the first prompt is false? Im trying to conditionally render certain prompts. I may have different flows through steps depending on the previous prompt responses, as you can do on the CLI.

**Comment by slavik-lvovsky** [comment]
Not a bug. It should work even in one prompt
