### ISSUE TITLE
Error running the backend : npm run ws:run

### ISSUE THREAD

**Issue by ravi4j** [SAP/yeoman-ui#153]
The npm compile is generating javascript in the out/src folder. Due to this, the npm run ws: run command fails to execute as it is looking source directly inside the out folder.

Fix : package.json is missing src folder 
"ws:run": "node ./out/**src**/webSocketServer/index.js",

npm ERR! yeoman-ui@0.0.40 ws:run: `node ./out/webSocketServer/index.js`

**Comment by tomer-epstein** [comment]
https://github.com/SAP/yeoman-ui/pull/154 Merged.
