### ISSUE TITLE
updating the answers object in question func (when, default,validate ...) doesn't wok.

### ISSUE THREAD

**Issue by tomer-epstein** [SAP/yeoman-ui#205]
![image](https://user-images.githubusercontent.com/57438361/77845265-23648c00-71b6-11ea-9e37-5c1923a02597.png)

**Comment by tomer-epstein** [comment]
a solution for this issue is using the ‘options’ param to pass the previous answers.

![image](https://user-images.githubusercontent.com/57438361/77845490-ff09af00-71b7-11ea-9647-e1b87dee5789.png)

**Comment by IainSAP** [comment]
@tomer-epstein I have found a way to workaround by this (similarly) this.props in the validators, however it's questionable if the behaviour of the code should be different between the CLI and running in Yeoman-UI.

**Comment by tomer-epstein** [comment]
https://github.com/SAP/yeoman-ui/pull/268

We apply the default value/function when the form is loaded, and even while the user changes the value of another question. However, we do not do this when the question is dirty.

We introduce a 'guOption.applyDefaultWhenDirty' property. this will apply the default value when the question is dirty.

Released at version 1.0.3
