### ISSUE TITLE
Generator name without scope giving 404 error in app studio

### ISSUE THREAD

**Issue by Satvindar** [SAP/yeoman-ui#236]
Hi,

Steps to reproduce the issue:
Published yeoman generator with name '**generator-serverless-extensions**' in artifactory. 
Then, I included the same under yeoman-packages inside extension-data.json as shown below code snippet. 

 "npmConfig": {
    "registries": {
      "xfsrt": "https://common.repositories.sap.ondemand.com/artifactory/api/npm/generator-faas/"
    }
  },
  "yeomanPackages": [
    {
      "name": "@xfsrt/generator-serverless-extensions",
      "versionRange": "1.0.3",
      "artifactory": "npm"
    }
  ]

Deployed the extension in our subaccount and created a dev space using this extension.
Clicked on dev space and opened the workspace.
In output console, we  get an error:  **404 Not Found - GET https://common.repositories.sap.ondemand.com/artifactory/api/npm/generator-faas/@xfsrt%2fgenerator-serverless-extensions - not_found
npm ERR! 404**. Can yu please look into this issue?

**Comment by tomer-epstein** [comment]
Closing the issue since it's not seems related to yeoman-ui.
