### ISSUE TITLE
Empty answer should be an empty string

### ISSUE THREAD

**Issue by perspectivus1** [SAP/yeoman-ui#26]
When running `yo code`  from the terminal, and leaving the *Description* empty, an empty string `""` is created in the `package.json`.

When running the `code` generator using `yeoman-ui`, an empty value is created in the `package.json`, which makes it an invalid json, which in turn, fails the `npm install` stage.

**Comment by tomer-epstein** [comment]
https://github.com/SAP/yeoman-ui/pull/30
