### ISSUE TITLE
debug console warning - memory leak detected.

### ISSUE THREAD

**Issue by tomer-epstein** [SAP/yeoman-ui#283]
(node:508764) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
warning.js:32
(node:508764) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
warning.js:32
(node:508764) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
warning.js:32
(node:508764) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
warning.js:32
(node:508764) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
warning.js:32
(node:508764) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

**steps to reproduce - (Next -> Back ) * 10**

**Comment by ira-gordin-sap** [comment]
This exactly an issue I've found in the logger https://github.com/SAP/vscode-logging/issues/76 and fixed in the version 1.1.0.
I see that current "@vscode-logging/logger": "1.1.0" so it should be ok.
Is the issue still reproducible?

**Comment by tomer-epstein** [comment]
@slavik-lvovsky can we close this issue?
