### ISSUE TITLE
List items not re-rendered correctly when choices updated

### ISSUE THREAD

**Issue by IainSAP** [SAP/yeoman-ui#288]
Changing the contents of a list dynamically, where an item has been previously selected results in an incorrectly rendered list with only one item. Once the user interacts with another control the list is re-rendered with the correct items.

**Comment by tomer-epstein** [comment]
Do you have a sample code that reproduce the issue?

It didn't reproduced with these questions.
{
    type: "list",
    name: "countryCode",
    message: "Your country code",
    choices: [
      { name: "+1", value: 1 },
      "+49",
      { name: "+86", value: 86 },
      { name: "+972", value: 972 }
    ],
    default: 86
  },
  {
    type: "list",
    name: "countryCode2",
    message: "Your country code2",
    guiOptions: {
      hint: "Please select your country code"
    },
    choices: function (answers) {
      return answers.countryCode === 972 ?
        [
          { name: "+1", value: 1 },
          "+2",
          { name: "+3", value: 3 },
          { name: "+4", value: 4 }
        ] :
        [
          { name: "+10", value: 10 },
          "+9",
          { name: "+8", value: 8 },
          { name: "+7", value: 7 }
        ];
    }
  },

**Comment by tomer-epstein** [comment]
https://github.com/SAP/yeoman-ui/releases/tag/v1.0.17
