### ISSUE TITLE
Field validation errors messages are subtle

### ISSUE THREAD

**Issue by ianquigley-sap** [SAP/yeoman-ui#307]
Feedback from users of the Application generator is that the inline validation of input fields is too subtle.  As an example:

![image](https://user-images.githubusercontent.com/15449680/85690819-dbc5a180-b6cb-11ea-9293-4899562541b1.png)

People are missing the "Module name cannot contain capital letters" message.  Can this error be made more visual?  Perhaps some highlighting of the associated invalid field would help?

**Comment by tomer-epstein** [comment]
UX Design - 

![image](https://user-images.githubusercontent.com/57438361/87240887-32e6a880-c426-11ea-8185-aab45efb310b.png)
