### ISSUE TITLE
Yeoman UI Wizard should say that no generators are currently installed 

### ISSUE THREAD

**Issue by helencorrigan** [SAP/yeoman-ui#308]
![image](https://user-images.githubusercontent.com/57438361/85976661-ab3f7980-b9e3-11ea-8d7a-d659685c72e8.png)

**Comment by helencorrigan** [comment]
I believe there is a delay between the vsix extensions been installed and setup and when the app generator tgz is installed, and so at times the app generator is not available in the wizard, as shown in the example above.

Therefore the confirmation message to confirm the extensions are ready for use, needs to wait for the app generator tgz to be fully installed before this confirm message is shown to the end user.

**Comment by vareevijay** [comment]
I am facing the same issue . How do we solve the problem?

**Comment by tomer-epstein** [comment]
@vareevijay please have a look at https://github.com/SAP/yeoman-ui/issues/309

**Comment by idoprz** [comment]
I also suggest to add to that message also a button to the upcoming generator explorer feature, since most users will need to install one.

**Comment by tomer-epstein** [comment]
![image](https://user-images.githubusercontent.com/57438361/86286364-fda0b600-bbee-11ea-8659-696b1f250cbe.png)
