### ISSUE TITLE
Not able to view the Generator in VS Code Mac

### ISSUE THREAD

**Issue by raja83v** [SAP/yeoman-ui#309]
Hi,
I am not able view the Generators option in VS Code (Mac OS) after selecting SAP FIORI Application Generator tool.
![image](https://user-images.githubusercontent.com/58028337/85835670-ca1df000-b7d8-11ea-9683-812e33708db4.png)

**Comment by ianquigley-sap** [comment]
@raja83v can you please ensure you have the application generators installed correctly?  Please ensure you have node installed and open a terminal and execute:

```
npm i -g @sap/generator-fiori-elements --@sap:registry=https://registry.npmjs.org
```

That should ensure the generators are installed from the correct repository.

**Comment by raja83v** [comment]
@ianquigley-sap Thanks a lot. After following the above mentioned steps, it resolved the issue.

**Comment by vareevijay** [comment]
Thanks for the reply . I am relatively new to this. It shows certificate error.

![image](https://user-images.githubusercontent.com/65146427/86088556-6fe09180-ba5b-11ea-8c72-ddcf128b88c6.png)

**Comment by ianquigley-sap** [comment]
@vareevijay you may need to discuss this with your local IT.  One solution may be to execute the following:

```
npm config set strict-ssl false
```

**Comment by vareevijay** [comment]
@ianquigley-sap  - Worked like a charm. Thanks a lot.

**Comment by abgunes** [comment]
> @raja83v can you please ensure you have the application generators installed correctly? Please ensure you have node installed and open a terminal and execute:
> 
> ```
> npm i -g @sap/generator-fiori-elements --@sap:registry=https://registry.npmjs.org
> ```
> 
> That should ensure the generators are installed from the correct repository.
> 
> Please restart VScode afterwards.

That's worked for me, thanks for answer.

**Comment by danielfruiz-cl** [comment]
> @raja83v can you please ensure you have the application generators installed correctly? Please ensure you have node installed and open a terminal and execute:
> 
> ```
> npm i -g @sap/generator-fiori-elements --@sap:registry=https://registry.npmjs.org
> ```
> 
> That should ensure the generators are installed from the correct repository.
> 
> Please restart VScode afterwards.

Thank you very much! Did this happened because we didn't install the npm for CDS in CAP?

Cheers!
