### ISSUE TITLE
Dynamically populating list option

### ISSUE THREAD

**Issue by sushiljain1989** [SAP/yeoman-ui#335]
On a single page,  I have three list boxes:
ListA
ListB
ListC

Is it possible to dynamically load the options in ListB if I select any option in ListA and the same behavior with ListB and ListC?
Note: Options will be fetched from a REST Api call.

**Comment by tomer-epstein** [comment]
Hi @sushiljain1989 ,
Here's an example of dynamic choices based on previous question answer.

  {
    type: "list",
    name: "countryCode",
    message: "Your country code",
    choices: [
      { name: "+1", value: 1 },
      "+49",
      { name: "+86", value: 86 },
      { name: "+972", value: 972 }
    ],
    default: 86
  },
  {
    type: "list",
    name: "countryCode2",
    message: "Your country code2",
    default: function (answers) {
      return (answers.countryCode === 1) ? undefined : "+0";
    },
    guiOptions: {
      applyDefaultWhenDirty: true,
      hint: "Please select your country code"
    },
    choices: function (answers) {
      return answers.countryCode === 972 ?
        [
          "+0",
          { name: "+1", value: 1 },
          "+2",
          { name: "+3", value: 3 },
          { name: "+4", value: 4 }
        ] :
        [
          "+0",
          { name: "+10", value: 10 },
          "+9",
          { name: "+8", value: 8 },
          { name: "+7", value: 7 }
        ];
    }
  },
