### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mmarkvillanueva** [SAP/yeoman-ui#353]
- Issue Type: `Performance`
- Extension Name: `yeoman-ui`
- Extension Version: `1.1.7`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\mvillanuev29\SAPOS.yeoman-ui-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by tomer-epstein** [comment]
@mmarkvillanueva can you please make sure to upload the <myExtensionId>.cpuprofile.txt-file.

**Comment by tomer-epstein** [comment]
@mmarkvillanueva issue will be close in 7 days if no response.
