### ISSUE TITLE
Cannot list Generators in Yeoman UI until reload window

### ISSUE THREAD

**Issue by GabbyChang** [SAP/yeoman-ui#358]
Reproduce steps:
1. Installed one generator globally in local. Open one VSCode window
2. From the Command Palette execute the command: **SAP Fiori tools - Application Generator: Launch**
3. Check no Generators listed as below
![yeoman-ui-1](https://user-images.githubusercontent.com/7637430/91940750-8db3c680-ed2a-11ea-9ab0-e9753cf01096.png)
4. From the Command Palette execute the command: **Developer: Reload Window**
5. Check all the available Generators are listed as expected:
![yeoman-ui-2](https://user-images.githubusercontent.com/7637430/91940771-96a49800-ed2a-11ea-987e-c8f49fb80e82.png)

**Expected result:**
All the generators installed globally should be listed in Yeoman UI directly after open it.

**Actual result:**
The generators are not listed until user execute reload command.

**Comment by tomer-epstein** [comment]
+ @IainSAP 
It seems that 'developer reload windows'  launch the yeoman-ui without filter. That's why all generators installed on the machine appears.

**Comment by tomer-epstein** [comment]
@GabbyChang which generator did you installed globally?

**Comment by GabbyChang** [comment]
@tomer-epstein I installed several generators as in the second screenshot. The generator Baf and Baf-generator are developed by our team. The Code generator is the public generator [**generator-code**](https://www.npmjs.com/package/generator-code) , which is installed by command: _npm install -g yo generator-code_
As you said, **It seems that 'developer reload windows' launch the yeoman-ui without filter**, does it mean my installed generators on the machine will be filter out? From my understanding, all the generators installed globally will be listed once open the Yeoman UI. Please correct me if misunderstanding.

**Comment by tomer-epstein** [comment]
@GabbyChang you have choose to run the command: SAP Fiori tools - Application Generator: which launch the wizard with filter of only fiori tools generators.
Your generators does not have this filter.
If you want to see all installed generators please run 'yeomn ui' view command.

**Comment by GabbyChang** [comment]
@tomer-epstein Thanks a lot for your support, I can get all generators from my local machine.
