### ISSUE TITLE
Doesn't support sub-generator

### ISSUE THREAD

**Issue by GabbyChang** [SAP/yeoman-ui#365]
From our generator, we defined several sub-generators for different questions and actions. And we don't maintain any steps in main generator. 
Then when we use Yeoman UI, there will be nothing display after click Next button.
So is it possible to support sub-generators with Yeoman UI?

**Comment by slavik-lvovsky** [comment]
There is no problem to use sub-generators in Yeoman UI.
Even if there are no questions in your manin generator, Yeoman UI will show questions coming from your sub-generators.

**Comment by idoprz** [comment]
Hi Gabby,
As Slavik said, we support sub-generators. If you encounter problem there, can you send us the code or some way to reproduce?

**Comment by GabbyChang** [comment]
Hi Ido,
The generator we used is located at: https://github.wdf.sap.corp/BIG/generator-baf-scripts, which only has several sub-generators.
The reproduce steps as below. I installed extension Application Wizard. Trigger it and select the generator with **Baf Scripts**, it starts to loading as below:
![loading](https://user-images.githubusercontent.com/7637430/93057937-41a94000-f6a1-11ea-86fe-f0f883d7dea3.png)
After loading finished:
![after loading](https://user-images.githubusercontent.com/7637430/93058003-5c7bb480-f6a1-11ea-8be1-acb37cbc2573.png)
Click Open in New Workspace:
![open new workspace](https://user-images.githubusercontent.com/7637430/93058101-7a491980-f6a1-11ea-9861-5ad19cd8ff81.png)
No sub-generators to select and no application generated.

Thanks,
Gabby

**Comment by idoprz** [comment]
Hi Gaby,
We do support running sub-generators as part of the main generator.
The discovery of generators currently supports showing only the parent generators.
Right now, we still do not support running a specific generator or sub generator directly from UI (like from cli running "yo gen" or "yo gen:subgen") without going through the discovery step. Once we will support running generators directly from UI we should also support running sub generators.
We can add a requirement to show sub generators in the discovery page as well.

Thanks,
Ido.

**Comment by GabbyChang** [comment]
Hi Ido,
So currently it supports to compose other sub-generators with main generator, just like the foodq example that main generator compose with app2. Right?
Also yes, please add that showing sub generators in the discovery page as a requirement, or the user has to manually maintain the relationship between sub-generators and main generators.
Thanks very much for your support.

Thanks,
Gabby

**Comment by idoprz** [comment]
Yes, the app2 in foodq is a good example.
I can suggest that for now, you add a question of type list with guiOptions type "tiles" to the main generator. This question can ask the user which sub-generator to run. It will show up in the UI as tiles.

Thanks,
Ido.

**Comment by slavik-lvovsky** [comment]
We have added "Run Generator" command that runs any main/sub generator.
It was introduced in version 1.1.48
