### ISSUE TITLE
Running on Nginx Raspberry Pi

### ISSUE THREAD

**Issue by Cre8tiveDigital** [SAP/yeoman-ui#376]
Hi there, first of all, I would like to say this application is fantastic. Just what I have been looking for.

My issue,
I have had the application running fine on my machine, however, I have installed it on to raspberry pi with an Nginx server running as I tried using the method described in the read me of starting webpack and WebSocket and then serve in the frontend. when I did this I could see the application working on the raspberry pi desktop but when I try and navigate to it vier the network address I am given I just get a blank page. 
![Screenshot-2020-10-01-at-10 01 39](https://user-images.githubusercontent.com/33846654/94790095-bbde0200-03cd-11eb-9987-78a18d8aa60b.png)
The reason I would like to use on a web server is so that I can have it running for all devs in a central location so when I do updates to generators they all have access to the most up to date versions without having to rely on them pulling from git.

This issue may e something I am doing wrong or just may not be a capability of the application. It is not capable of been run this way is there any thoughts of developing a version that can be run in this way. 

Thanks for your time in building this amazing application and thanks in advance for any help you may be able to offer.

**Comment by idoprz** [comment]
Hi,
Right now, our main focus is to deliver this application as a VSCode extension. For us, the use of the browser is mainly for development purposes. So we usually test it via localhost only.

We do see in our roadmap official support for consuming it in the browser from the network, but this is not our main focus right now.

To try and support you, can you provide some more information? Do you see any errors on the chrome dev-tools?
Also, can you elaborate on your usecase? Since the server generates the project, can you explain how you intend the users to get the generated project?

**Comment by Cre8tiveDigital** [comment]
Hi Ido, 
Thanks for the reply, I kinda thought you would be concentrating on the VSCode version my only issue with that is the dev's I work with don't like to use VSCode. 

For my use case - 
Ideally, once the project is scaffolded the application would generate a download the project. Then a separate script would run once a week to clean out the project folder to save space on the Raspberry Pi. 

But for now, the generates I have built automatically push new projects to our GitLab instance so the projects can be cloned from there, as a current workaround.  

Errors - 
I am seeing errors in crome and they are as follows 
App.vue:432 WebSocket connection to 'ws://127.0.0.1:8081/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Thanks for your help

**Comment by idoprz** [comment]
Currently we are "hard coding" the host to 127.0.0.1.

Can you explain your landscape? Are you using nginx as web server to serve the static resources? do you use nginx as router for the backend as well?

**Comment by Cre8tiveDigital** [comment]
I have desided to move to using VS code thanks for your help on this.
