### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by tomer-epstein** [SAP/yeoman-ui#38]
- promise rejects while performing rpc calls
- ensure callback of Generator.run() is called when user aborts during conflict resolution and when exceptions occur

**Comment by tomer-epstein** [comment]
https://github.com/SAP/yeoman-ui/pull/37

**Comment by perspectivus1** [comment]
Partial support for error handling here: https://github.com/SAP/yeoman-ui/pull/37

**Comment by tomer-epstein** [comment]
https://github.com/SAP/yeoman-ui/pull/41
