### ISSUE TITLE
Cannot read Property

### ISSUE THREAD

**Issue by Cre8tiveDigital** [SAP/yeoman-ui#406]
Hi, am having an issue after building my own generator regarding prompts from a parent generator yo a sub-generator. 

I have followed the foodq example and have implemented the constructors and initialisation steps and the prompting seams to work. The issue I am facing is that when the generator run's I get an error relating to "this.parentPromptsQuantity = this.prompts.size();" the error is as follows "Cannot read property 'size' of undifined\n\tat New module.exports". 

I have looked through the foodq example and cant see what I have done wrong.

Any help with this would be appreciated. 

Thank's

**Comment by Cre8tiveDigital** [comment]
Does anyone have an insight on the above issue. any help would be appreciated!

**Comment by idoprz** [comment]
can you provide a code sample to reproduce it?

**Comment by Cre8tiveDigital** [comment]
The Original question here can be closed. But I do have another issue. I am attempting to write a yeoman generator and I have one prompt that asks whether the user requires multiple versions of the project, when the answer to this confirm prompt is true the user is then shown a new input requiring a number of versions required. When I test this and input 2 for instance yeoman online generates the one version. 

I know this is more likely a yeomen question and not an Application Wizard one but I am rebuilding my original generator to work and look nice in Application Wizard, I have been following the example generator. I can share code if required (Privately as NDA). 

Any help on this would be much appreciated.

**Comment by Cre8tiveDigital** [comment]
I have worked out this issue closeing the ticket on this thanks
