### ISSUE TITLE
Yeoman UI don't show "Foodq" generator

### ISSUE THREAD

**Issue by hauntedhill** [SAP/yeoman-ui#440]
Hello,

i try to show the example generator "Foodq" in the yeoman UI in VSCode 1.51.1. My version of the Application Wizard is "1.1.38".
NPM Version: 6.12.0, Node Version: 12.13.0, all on Windows 10.

My is problem ist that the generator "foodq" is not shwon in the Yeoman UI. I have copied the sources of "foodq" in my global node_modules folder but nothing happend. If i type in the console "yo" then the "foodq" generator is shown and i can use it without any problems.

I have set auto update to false in the settings and i setup the installation location of the generators to my global node_modules folder but nothing changed, the generator is still not shown.

Is this a bug or need the example generator additional configuration?

Thanks and Regards

Haunted

**Comment by tomer-epstein** [comment]
Please try 'npm link' command at the generator-foodq folder.

**Comment by hauntedhill** [comment]
Hi,

i am sorry i used this command too. But i found a solution. But i am not sure if this is a bug or it is something for the documentation.

I added the statement:

 "generator-filter": {
    "type": "tools-suite",
    "types": [
      "tools-suite",
      "project"
    ]
  }

to the packahe.json of the foodq generator and now it works. This statement is missing in the repository version of package-json.

Regards

Haunted

**Comment by tomer-epstein** [comment]
What is the command that you have run in order to see the 'yeoman-ui' ?
Mu assumption is that you have run a command that filters only generator of type "tools-suite".

**Comment by hauntedhill** [comment]
To see the yeoman-ui i used the command "yo" in the console, In my console all generators are shwon. 

If i execute the yeoman-ui in my Visual StudioCode (strg + shift + P => Fiori: Open Application Generator) then the generators are not shown.

But now i added the filter setting and all generators are shown in the the visual code yeoman-ui too.

**Comment by tomer-epstein** [comment]
This is 'as designed'.
The command "Fiori: Open Application Generator" filters only generators with type "tools-suite"
The command "Yeoman UI Generators" shows all yeoman generators available.
