### ISSUE TITLE
More of a Yeoman question

### ISSUE THREAD

**Issue by Cre8tiveDigital** [SAP/yeoman-ui#493]
This is more of a yeoman question, but as you guys are the yeoman masters I thought I would ask here. Is there a way I can set the ```copy(this.templatePath)``` or ```copyTpl(this.templatePath)``` to a URL instead of a locally stored file. 

The reason I would want to do this is so I can keep template files updated on something like Gitlab/Github and not require the user to update their generator each time a template file is updated. 

I look forward to your response.

**Comment by tomer-epstein** [comment]
Hi @Cre8tiveDigital,

As to the yeoman documentation, the 'Template' context is locally.
https://yeoman.io/authoring/file-system.html

I haven't check this yet, but assume that you can create an HTTP GET request and pipe its response into a writable file stream located at the  'Template' path.

Regards,
Tomer
