### ISSUE TITLE
View the log from when a generator runs.

### ISSUE THREAD

**Issue by PhilipMugglestone** [SAP/yeoman-ui#496]
Hi,

Wondering whether it's possible (and how) to view the log from when a generator runs?

Basically everything written by the generator to `this.log`.

Thanks,

**Comment by tomer-epstein** [comment]
Hi @PhilipMugglestone ,

To view the log please open output and select 'Application Wizard.Generators'

Regards, Tomer

![image](https://user-images.githubusercontent.com/57438361/107870425-ee7e2800-6ea0-11eb-9533-3ecd4b4dbbe9.png)

**Comment by PhilipMugglestone** [comment]
Hi @tomer-epstein 

Perfect! Thanks.

Regards,

Philip
