### ISSUE TITLE
Issue: Error: Cannot find module 'vscode'

### ISSUE THREAD

**Issue by raoxisme** [SAP/yeoman-ui#516]
Hi Expert,

The idea of feature of yeoman-ui looks really perfect. When follow the step 'npm run ws:run' mentioned in the backend folder
https://github.com/SAP/yeoman-ui/tree/master/backend

it always gives an error:
> node ./out/src/webSocketServer/index.js
internal/modules/cjs/loader.js:834
  throw err;  ^
Error: Cannot find module 'vscode'

It doens't help even execute 'npm install vscode -g' before execution.

Does anyboday have same issue?

Best regards,
Wei

**Comment by tomer-epstein** [comment]
Hi @raoxisme,

To debug the yeoman-ui backend launch vscode:

1.  in the debug pane select 'Run Extension'
![image](https://user-images.githubusercontent.com/57438361/111030866-40b55900-840d-11eb-981b-8a872cdfff88.png)

1. then click 'F1' and select 'Open Template wizard'
![image](https://user-images.githubusercontent.com/57438361/111030912-807c4080-840d-11eb-8e73-e0edd41cdf5b.png)

Best regards,
Tomer

**Comment by raoxisme** [comment]
Hi Tomer,

Thanks for the suggestion. In this way, it is working running as VSC extension debugging mode.

The only pity is, running the framework in the browser using vue cli doesn't work, which may help non-dev user to leverage this great tool.
Actually it was working weeks ago, not clear why not work for now. I tried to adjust engines:vscode in package.json to latest version 1.54.2, seems not the case.

Best regards,
Wei

**Comment by jaryway** [comment]
@tomer-epstein the problem occurs again in version 1.7.11，but version 1.7.10 is fine!
