### ISSUE TITLE
Thenable for Yeoman UI completion is missing

### ISSUE THREAD

**Issue by UladzislauYurhel** [SAP/yeoman-ui#528]
We recently implemented the basics of the UI using the Yeoman UI and the associated developed generators. After testing, there was a question about the processing of the completed filling of the Yeoman UI by the clients.

Using the `await vscode.commands.executeCommand('loadYeomanUI', { generator: 'migration' });` we initialize the required generator to display needed sections/fields to fill from the client-side. But right after the client provided some credentials in that sections, we need to run another method using await `runMain();`. So, the full snippet looks like:

<pre language="java">
let disposable = vscode.commands.registerCommand('${COMMAND_PREFIX}.start', async function (uri) {
        try {
            basPreChecker.basEnvWorkspaceFoldersPreCheck(vscode.workspace.workspaceFolders);

            <b>await vscode.commands.executeCommand('loadYeomanUI', { generator: 'migration' });</b>

            <b>await runMain();</b>
        } catch (err) {
            vscode.window.showErrorMessage(err.message);
        }
});
</pre>

The main issue here is that the `await runMain();` executes itself right after the UI is initialized and does not wait for the final completion of UI filling in the fields/sections. As far as I understand this is the correct behavior, but the next question is: **how can we pass the runMain command execution to manage it somehow from the Yeoman UI completion perspective**? (for example, execution callback or something else).

Thanks!

**Comment by slavik-lvovsky** [comment]
Hi,

Basically Yeoman UI displays the same questions as yo cli does.
When you develop your generator it should work in both Yeoman UI and yo cli.

How and when do you execute your runMain function if you run the generator in yo cli ?

We do have an option to pass some custom data to the loadYeomanUI command. This data object will be forwarded to your generator.
This is an example to get the data you passed in loadYeomanUI command:
https://github.com/SAP/yeoman-ui/blob/02d61d539b4ed7c5db07519306d883696034f481/generator-foodq/generators/app/index.js#L14

Example of how to pass the data to your command:
const myData = {
      user: "user",
      password: "password"
    };

    
      await commands.executeCommand("loadYeomanUI", {
        data: myData
      });
  
You should execute runMain() function to fill the data object before the command execution.

**Comment by UladzislauYurhel** [comment]
For the time being we've found a little workaround for that. Because this comment is not suitable for our case, we need to execute the `runMain()` right after all the credentials are filled. So, we decided to run it at the latest generator step in the `writing` method (I'm not sure that this is the right direction for that, but it works).

**Comment by slavik-lvovsky** [comment]
We will fix the issue with not async commands, it is in our nearest plans.
The last generator step is "end", may be it is better for your case.
