### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/yeoman-ui#534]
- Issue Type: `Performance`
- Extension Name: `yeoman-ui`
- Extension Version: `1.1.57`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\pplenkov\AppData\Local\Temp\1\SAPOS.yeoman-ui-unresponsive.cpuprofile.txt
[SAPOS.yeoman-ui-unresponsive.cpuprofile.txt](https://github.com/SAP/yeoman-ui/files/6220681/SAPOS.yeoman-ui-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ThePlenkov** [comment]
[SAPOS.yeoman-ui-unresponsive.cpuprofile.txt](https://github.com/SAP/yeoman-ui/files/6220691/SAPOS.yeoman-ui-unresponsive.cpuprofile.txt)

**Comment by slavik-lvovsky** [comment]
Thank you for reporting the issue.
We are planning to start fixing it soon.

**Comment by karpovas1505** [comment]
Hi @slavik-lvovsky, i have the same issue.
When you plan fix it?

**Comment by slavik-lvovsky** [comment]
Fixed in version 1.3.1
