### ISSUE TITLE
SSO to on premise ABAP

### ISSUE THREAD

**Issue by ShortCutNinja** [SAP/yeoman-ui#549]
I am not able lo log into on premise ABAP system with SSO

![image](https://user-images.githubusercontent.com/18305781/113998663-90930e80-9859-11eb-99d9-1c3e4c4b4cb6.png)

**Comment by tomer-epstein** [comment]
Hi @ShortCutNinja 
This issue is specific to the template generator being run.
Please open an internal jira ticket on this template component.
Regards, Tomer

**Comment by ShortCutNinja** [comment]
hi @tomer-epstein, may you please guide me to the jira project?
