### ISSUE TITLE
Backend is failing to start due to RpcExtenstionWebSockets and RpcEx

### ISSUE THREAD

**Issue by ravi4j** [SAP/yeoman-ui#58]
Backend server is not starting and failing due to misspell RpcExtenstion , RpcExtensionWebSockets in two source code files
extension.ts
webSocketServer/index.ts

import { RpcExtenstionWebSockets } from '@sap-devx/webview-rpc/out.ext/rpc-extension-ws';
import { RpcExtenstion } from '@sap-devx/webview-rpc/out.ext/rpc-extension';

![issue1](https://user-images.githubusercontent.com/8282950/71189147-f2d09600-2247-11ea-939f-782cc03e9a7d.PNG)

![issue2](https://user-images.githubusercontent.com/8282950/71189227-1693dc00-2248-11ea-9072-05cf32b2a3ef.PNG)

Please correct these two errors or allowing me to commit the fix.

**Comment by idoprz** [comment]
Fixed
