### ISSUE TITLE
yoeman generator-generator and others - Cannot read property 'stdout' of null

### ISSUE THREAD

**Issue by abulka** [SAP/yeoman-ui#623]
Running yoeman generator-generator I get an error relating to 'Cannot read property 'stdout' of null'.  I wonder if this is because my node is installed via `nvm` - or is it a general problem?

## generator-generator

```json
{
   "message":"generator:app generator failed - process.on(uncaughtException) process.on(uncaughtException) Cannot read property 'stdout' of null",
   "stack":"TypeError: Cannot read property 'stdout' of null\n\tat Object.user.git.name (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-generator/node_modules/generator-node/node_modules/yeoman-generator/lib/actions/user.js:30:70)\n\tat module.exports._askFor (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-generator/node_modules/generator-node/generators/app/index.js:195:32)"
}
```

I tried some other generators:

## code

Running the built in vscode extension generator walks me through the options ok but ultimately gives the error

```
{"message":"code:app generator failed - env.on(error) Command failed with exit code 1: npm install","stack":"Error: env.on(error) Command failed with exit code 1: npm install\n\tat e.exports (/Users/andy/.vscode/extensions/sapos.yeoman-ui-1.3.1/dist/extension.js:2:2272822)\n\tat /Users/andy/.vscode/extensions/sapos.yeoman-ui-1.3.1/dist/extension.js:2:2270272\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)"}
```

## generator-electron-flask

This is my own generator https://github.com/abulka/generator-electron-flask, which I have npm linked to a development directory. Running this I get 3 exceptions popping up e.g.

```
{"message":"electron-flask:app generator failed - gen.on(error) Cannot read property 'stdout' of null","stack":"TypeError: gen.on(error) Cannot read property 'stdout' of null\n\tat Object.user.git.name (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/node_modules/yeoman-generator/lib/actions/user.js:30:70)\n\tat module.exports.prompting (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/generators/app/index.js:61:32)\n\tat Object.<anonymous> (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/node_modules/yeoman-generator/lib/index.js:424:27)\n\tat /Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/node_modules/run-async/index.js:49:25\n\tat new Promise (<anonymous>)\n\tat /Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/node_modules/run-async/index.js:26:19\n\tat /Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generat...
```

and

```
{"message":"test-1:app generator failed - process.on(uncaughtException) env.on(error) gen.on(error) Cannot read property 'stdout' of null","stack":"TypeError: gen.on(error) Cannot read property 'stdout' of null\n\tat Object.user.git.name (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/node_modules/yeoman-generator/lib/actions/user.js:30:70)\n\tat module.exports.prompting (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/generators/app/index.js:61:32)\n\tat Object.<anonymous> (/Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/node_modules/yeoman-generator/lib/index.js:424:27)\n\tat /Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/node_modules/run-async/index.js:49:25\n\tat new Promise (<anonymous>)\n\tat /Users/Andy/.nvm/versions/node/v12.18.3/lib/node_modules/generator-electron-flask/node_modules/run-async/index.js:26:19\n\tat /Users/Andy/.nvm/versions/no...
```

**Comment by slavik-lvovsky** [comment]
Please check again with the latest version 1.4.5.
Currently you use 1.3.1

**Comment by abulka** [comment]
Same errors in 1.4.5

**Comment by slavik-lvovsky** [comment]
I also use nvm
The latest version works as expected with code and generator generators
![image](https://user-images.githubusercontent.com/5508128/122739166-64e5c900-d28b-11eb-83f0-3d32bbc060de.png)

**Comment by slavik-lvovsky** [comment]
for your generator I got the error you mentioned:
![image](https://user-images.githubusercontent.com/5508128/122741950-27cf0600-d28e-11eb-8388-3dc2f7623f8d.png)

**Comment by slavik-lvovsky** [comment]
it fails in this line: https://github.com/yeoman/generator/blob/357932222b7806e6d3e60c44d5cbdd9b2da74dcf/lib/actions/user.js#L29

Your generator does work with yo cli.
I think that lib/actions/user.js can not run without terminal, need to investigate it.

**Comment by abulka** [comment]
> Your generator does work with yo cli.

I type 'yo electron-flask' all the time from the terminal and it works on all OSs. 

Nice to see my generator working in a UI - I think your vscode has great promise!

**Comment by slavik-lvovsky** [comment]
This issue is most probably caused by shelljs (yeoman-generator depends on it).
This is what I have found: https://github.com/shelljs/shelljs/wiki/Electron-compatibility   (vscode is based on Electron).

Anyway if you want to make you generator work now in the Application wizard just wrap this.user.git methods in try/catch and provide some default value in case of error.

**Comment by slavik-lvovsky** [comment]
I have implemented a workaround and now your generator should work.
Please install version 1.5.0
