### ISSUE TITLE
Error at Fiori: application generator: mkdir C:\\

### ISSUE THREAD

**Issue by davizeber** [SAP/yeoman-ui#624]
I'm getting the follow error:
{"message":"@sap/fiori:app generator failed - runGenerator() EPERM: operation not permitted, mkdir 'C:\\'","stack":"Error: runGenerator() EPERM: operation not permitted, mkdir 'C:\\'"}
![SharedScreenshot](https://user-images.githubusercontent.com/85937938/122826670-cd4b9f00-d2b9-11eb-8d7d-19d583398141.jpg)

Already reinstall extension packs.

Please help me to find where/which config set this 'C:\\'

**Comment by slavik-lvovsky** [comment]
Please try this solution: https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows/37915233#37915233
