### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by krishraheja** [SAP/yeoman-ui#640]
Hi Support,

I am getting the following error after selecting OData service.

{"message":"@sap/fiori:app generator failed - process.on(uncaughtException) Cannot read property 'edmx' of undefined","stack":"TypeError: Cannot read property 'edmx' of undefined\n\tat default_1.prompting (C:\\Users\\XXXXX\\node_modules\\@sap\\generator-fiori\\generators\\fiori-elements\\app\\index.js:2:5939697)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)"}

**Comment by slavik-lvovsky** [comment]
yeoman-ui just executes generators.
This error comes from the fiori:app generator and yeoman-ui just catched it. Edmx is part of fiori:app generator.
You need to contact fiori:app generator support.
