### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AndreAmaral82** [SAP/yeoman-ui#654]
- Issue Type: `Performance`
- Extension Name: `yeoman-ui`
- Extension Version: `1.4.5`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by slavik-lvovsky** [comment]
I do not see any problem related to high cpu load.
Please attach the needed profile file
![image](https://user-images.githubusercontent.com/5508128/126283912-4aff1174-48b1-4def-977a-944e5019cd64.png)

**Comment by slavik-lvovsky** [comment]
Please attach the needed profile file and reopen the ticket
