### ISSUE TITLE
@sap/fiori:app generator failed

### ISSUE THREAD

**Issue by arpit8105** [SAP/yeoman-ui#657]
Dear experts,

I have installed the "Application Wizard" in VS code but while launching it getting the below error-

![Vascdoe](https://user-images.githubusercontent.com/41038519/126496102-bf92534d-1db7-44ff-b8eb-eaa1df3d88b2.PNG)
![image](https://user-images.githubusercontent.com/41038519/126496167-534de5b8-c1ab-49f2-b51c-c4d32ba45be5.png)

Could you please assist?

**Comment by arpit8105** [comment]
Please note, I have node.js v14.16.1 version installed.

**Comment by slavik-lvovsky** [comment]
Please try this solution: https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows/37915233#37915233

**Comment by arpit8105** [comment]
Hi Slavik,
 Thank you for sharing the info but that did not help me.
is it possible if we can align somehow over Zoom?

**Comment by slavik-lvovsky** [comment]
Have you tried all options described in the above article ?

**Comment by arpit8105** [comment]
Hello Slavik,
Yes, i have tried all of them but still unable to resolve the error.
I have reinstalled node.js and VS code again also but no luck till now.

Can we discuss this over a Zoom call?

**Comment by slavik-lvovsky** [comment]
Let's do few more checks.
Go to File--> Preferences --> Settings --> Extensions --> Application Wizard --> Target Folder

Set your target folder to an existing folder on your machine.
Please update me whether it helps

**Comment by arpit8105** [comment]
Hello Slavik,
It worked. May I know the reason behind setting up a target folder. Earlier I never did that and still, it used to work.

**Comment by slavik-lvovsky** [comment]
From the error stack I saw that for some reason the target output folder of your generator is c:// and you have no permissions to create additional folders there. We just changed the target folder and it worked. I cannot tell why it worked before and does not work now, probably your permission settings have been changed.

**Comment by arpit8105** [comment]
Thank you for you help.
