### ISSUE TITLE
Getting error message and Template Wizard closes when trying to Connect to SAP system

### ISSUE THREAD

**Issue by smuhsb** [SAP/yeoman-ui#672]
Getting error message when generating a List Report Fiori Element App

![image](https://user-images.githubusercontent.com/8865800/127675224-ebc81094-a12b-402e-b280-3b39587cb907.png)

**Error Message**
![image](https://user-images.githubusercontent.com/8865800/127675338-a19f6aa0-6518-42f7-885c-dff098907a45.png)

**Comment by smuhsb** [comment]
`{"message":"@sap/fiori:app generator failed - {\"message\":\"Could not update method 'when' in 'selectedService' question in generator '@sap/fiori:app' - evaluateMethod() t.forEach is not a function\",\"stack\":\"TypeError: evaluateMethod() t.forEach is not a function\\n\\tat Object.t.getServiceChoices (C:\\\\Users\\\\v-muhsye\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\@sap\\\\generator-fiori\\\\generators\\\\fiori-elements\\\\app\\\\index.js:1:195694)\\n\\tat processTicksAndRejections (internal/process/task_queues.js:93:5)\\n\\tat async when (C:\\\\Users\\\\v-muhsye\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\@sap\\\\generator-fiori\\\\generators\\\\fiori-elements\\\\app\\\\index.js:1:204582)\"}"}`

**Comment by slavik-lvovsky** [comment]
This error comes from @sap/fiori:app generator. The wizard just displays it.
Please contact the generator developers.
