### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dfacode** [SAP/yeoman-ui#675]
- Issue Type: `Performance`
- Extension Name: `yeoman-ui`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.59.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\DELL\AppData\Local\Temp\SAPOS.yeoman-ui-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[SAPOS.yeoman-ui-unresponsive.cpuprofile.txt](https://github.com/SAP/yeoman-ui/files/7009325/SAPOS.yeoman-ui-unresponsive.cpuprofile.txt)

**Comment by slavik-lvovsky** [comment]
Please retest with version 1.7.1.
