### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by attilaberencsi** [SAP/yeoman-ui#693]
Hello,

using fiori generators, I am getting an exception:
{"message":"@sap/fiori:app generator failed - process.on(uncaughtException) Cannot read property 'edmx' of undefined","stack":"TypeError: Cannot read property 'edmx' of undefined\n\tat default_1.prompting (c:\\Users\\admin\\Desktop\\Software\\generators\\node_modules\\@sap\\generator-fiori\\generators\\fiori-elements\\app\\index.js:1:117696)\n\tat processTicksAndRejections (internal/process/task_queues.js:93:5)"}

using easy-ui5, a dialog to create this Issue was opened in VS Code. that is why I am here,BR,Attila 

[SAPOS.yeoman-ui-unresponsive.cpuprofile.txt](https://github.com/SAP/yeoman-ui/files/7481462/SAPOS.yeoman-ui-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `yeoman-ui`
- Extension Version: `1.7.3`
- OS Version: `Windows_NT x64 10.0.17763`
- VS Code version: `1.62.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\admin\AppData\Local\Temp\2\SAPOS.yeoman-ui-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by slavik-lvovsky** [comment]
1. The exception comes from the fiori generator. Please open an issue in the generator repository.

2. Please open a separate bug for the second issue with explanation how to reproduce it.
