### ISSUE TITLE
child process issue with yeoman-generator 5.7.0

### ISSUE THREAD

**Issue by floatinglee** [SAP/yeoman-ui#715]
To reduce the package size, we upgraded yeoman-generator to 5.7.0. 

In CLI mode, it works well, but encounter issues in yeoman-ui mode:
1) 'mdk migrate' costs more time. ( from 2 seconds to 1m)
https://github.wdf.sap.corp/snowblind/generator-mdk/blob/dev/generators/app/index.js#L149

2) no result from mdk build
seems it doesn't execute at all.
https://github.wdf.sap.corp/snowblind/generator-mdk/blob/dev/generators/app/index.js#L142

**Reproduce**:
1) install @sap/mdk-tools global

2) install generator-mdk 
git clone https://github.wdf.sap.corp/snowblind/generator-mdk.git
checkout **dev** branch
replace app/index.js#L149 by app/index.js#L142

install generator-mdk and run:

- select mdk generator
- empty template
- any project name
- use default value for others

a) it cost more time in mdk migrate.
b) no build result from  **Web/MDKModule** folder.
while run form terminal works well.

**Comment by bamba-bisli** [comment]
@alex-gilin are you familiar with this ?

**Comment by bd82** [comment]
@alex-gilin do you have any ideas regarding this?

**Comment by alex-gilin** [comment]
@floatinglee , please see below the yo cli output :
![image](https://user-images.githubusercontent.com/33512452/187762166-12b308cc-ff8c-4560-b385-535aa0e25eb4.png)
I'm missing something?

**Comment by floatinglee** [comment]
@alex-gilin , please install @sap/mdk-tools global

**Comment by bd82** [comment]
I wonder if this happens for any generator (which uses 5..70) that uses `const { execSync } = require("child_process");` 
when running under yeoman-ui.

I also wonder if this could be somehow related to yeoman-env versions

**Comment by floatinglee** [comment]
I tried to use generator.spawnCommandSync, it seems work well.

BTW:
spawnSync has same issue with execSync. 
All async can't work in yeoman-ui, like: exec, spawn, spawnCommand. Not sure if it's blocked by open in new workspace immediately.
