### ISSUE TITLE
Error message has hard-coded hex colour, instead of VS Code variable

### ISSUE THREAD

**Issue by gpeuc** [SAP/yeoman-ui#719]
Hello!

I have just noticed that errors are hard-coded red:

<img width="244" alt="Screenshot 2022-09-27 at 14 12 49" src="https://user-images.githubusercontent.com/44162846/192535870-3b9cc4a3-c289-4c75-b16e-5b6039ec62d1.png">

And hard-coded colours should not really exist in VS Code implementation.

The error should be:

`var(--vscode-errorForeground)`

as that will make it be correct colour depending on the theme.

Would it be possible to update this?

**Comment by alex-gilin** [comment]
@gpeuc thank you -> done.
