### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by gbmaes** [SAP/yeoman-ui#764]
Hi, it's been a week, maybe a bit longer, that I can't use the Application Wizard in VSCode anymore. I do what I usually do that used to work, which was openning it via shortcut command ctrl+shift+p. But now only a blank page is displayed when I open it. The extension is up to date.

**Comment by alex-gilin** [comment]
Hello @gbmaes ,
   can you see the list of available generators with the yeoman cli tool ``` yo --generators ``` ? if not, you just need to install some.
BR, AG

**Comment by gbmaes** [comment]
thanks, after installing the generators it is working again

**Comment by alex-gilin** [comment]
👍
