### ISSUE TITLE
Can I control the order of generators?

### ISSUE THREAD

**Issue by floatinglee2020** [SAP/yeoman-ui#766]
Hi,

I have a list of generators, and I want to highlight some. 
Can I configure the sequence from the main entry pane?

Regards
Zhenkun

**Comment by alex-gilin** [comment]
Hello @floatinglee2020 .
  Unfortunately, it is not possible to customize the order of generators. You get it like in yeoman cli one.
But if you want, there is an option to run the wizard with only a specific generator. See an example as follows:
```typescript
try {
   await vscode.commands.executeCommand("loadYeomanUI", { generator: "@ns/your-generator-id", messages: yourMessages, data: yourData });
  } catch (error) {
    logError(error);
  }
```
BR,AG

**Comment by floatinglee2020** [comment]
Hi alex, 

Thank you!

Regards
Zhenkun
