### ISSUE TITLE
Getting following error when "Opening template Wizard"

### ISSUE THREAD

**Issue by sbahad** [SAP/yeoman-ui#854]
Cannot read properties of Undefined ( reading 'getNodeProcessVersions' )

![error_Screen](https://github.com/user-attachments/assets/41ff3534-6543-4494-aac2-d0fc00d5a256)
![error_Screen](https://github.com/user-attachments/assets/30798a23-15af-4629-b28f-24a566b67325)

**Comment by rimasirich** [comment]
Hi, please try to update application wizard 1.16.7 it should include a fix that make it compatible to VSCode 1.94.0
