### ISSUE TITLE
Get ‘Cannot read properties of undefined (reading 'getNodeProcessVersions')“ when open Template Wizard.

### ISSUE THREAD

**Issue by Witwind** [SAP/yeoman-ui#855]
![image](https://github.com/user-attachments/assets/48d0b062-c1f4-4b9d-bb73-c4e3a75934ac)

**Comment by AlexNecula-Cashtriba** [comment]
Happening for me too. Also, when trying to generate a project I get the following message but nothing is installing.
![image](https://github.com/user-attachments/assets/956af1b4-1ad5-44f4-8e52-5f91c31c719f)

**Comment by veredcon** [comment]
Hi, please try to update application wizard 1.16.7 it should include a fix that make it compatible to VSCode 1.94.0
