### ISSUE TITLE
Not able to compile the backend on REL 7

### ISSUE THREAD

**Issue by ravi4j** [SAP/yeoman-ui#87]
src/extension.ts:183:41 - error TS2339: Property 'asWebviewUri' does not exist on type 'Webview'.
183             const scriptUri = this.panel.webview.asWebviewUri(scriptPathOnDisk); 

We have also tried to install vscode on the machine.

Please let me know any idea to resolve this issue.

**Comment by tomer-epstein** [comment]
This change has been done a month ago. We didn't experiance any issues.
https://github.com/SAP/yeoman-ui/commit/3a4680be4ac42a6e84bb4bc0ff58c238b37cc8bd
What is your development env ?

**Comment by ravi4j** [comment]
We are trying to deploy backend server on Red Hat Linux server 7. We are not able run backend server.

**Comment by tomer-epstein** [comment]
Please try to fork yeoman-ui repo.
Then revert the change done in extension.ts at -> https://github.com/SAP/yeoman-ui/blob/3a4680be4ac42a6e84bb4bc0ff58c238b37cc8bd/backend/src/extension.ts

**Comment by tomer-epstein** [comment]
Solution: https://github.com/SAP/yeoman-ui/pull/114
